/**
 * Detailed transit line routes with stations and waypoints.
 * Auto-generated by scripts/fetch-transit-routes.mjs via Google Routes API.
 * Generated: 2026-04-05
 */

export interface RouteStation {
  name: string;
  lat: number;
  lng: number;
}

export interface TransitLine {
  name: string;
  color: string;
  /** Stations in geographic order (first = furthest from venue) */
  stations: RouteStation[];
}

export const transitRoutesByVenue: Record<string, TransitLine[]> = {
  // ─── MetLife Stadium ─────────────────────────────────
  "metlife": [
    {
      name: "Newark - World Trade Center",
      color: "#d93a30",
      stations: [
        { name: "Penn Station", lat: 40.7341, lng: -74.1641 },
        { name: "~wp", lat: 40.7371, lng: -74.1589 },
        { name: "~wp", lat: 40.7411, lng: -74.1519 },
        { name: "~wp", lat: 40.7419, lng: -74.1392 },
        { name: "~wp", lat: 40.7432, lng: -74.1222 },
        { name: "~wp", lat: 40.7412, lng: -74.0877 },
        { name: "~wp", lat: 40.7381, lng: -74.0753 },
        { name: "Journal Square", lat: 40.7327, lng: -74.0627 },
        { name: "MetLife Stadium", lat: 40.8128, lng: -74.0742 },
      ],
    },
  ],

  // ─── SoFi Stadium ─────────────────────────────────
  "sofi": [
    {
      name: "Metro C Line",
      color: "#58a738",
      stations: [
        { name: "Avalon", lat: 33.9275, lng: -118.2652 },
        { name: "~wp", lat: 33.9288, lng: -118.2791 },
        { name: "Crenshaw", lat: 33.9252, lng: -118.3264 },
        { name: "~wp", lat: 33.9254, lng: -118.3367 },
        { name: "SoFi Stadium", lat: 33.9535, lng: -118.3392 },
        { name: "~wp", lat: 33.9326, lng: -118.3487 },
        { name: "Hawthorne / Lennox", lat: 33.9334, lng: -118.3517 },
        { name: "~wp", lat: 33.9332, lng: -118.3571 },
        { name: "~wp", lat: 33.9306, lng: -118.3658 },
        { name: "~wp", lat: 33.9303, lng: -118.3788 },
        { name: "Aviation / Century", lat: 33.9456, lng: -118.3787 },
      ],
    },
    {
      name: "Metro K Line",
      color: "#e56db1",
      stations: [
        { name: "Aviation / Century", lat: 33.9456, lng: -118.3787 },
        { name: "~wp", lat: 33.9579, lng: -118.3786 },
        { name: "~wp", lat: 33.9603, lng: -118.3773 },
        { name: "~wp", lat: 33.9654, lng: -118.3659 },
        { name: "~wp", lat: 33.9663, lng: -118.362 },
        { name: "~wp", lat: 33.9654, lng: -118.3569 },
        { name: "~wp", lat: 33.9653, lng: -118.3549 },
        { name: "Downtown Inglewood", lat: 33.9672, lng: -118.3515 },
        { name: "SoFi Stadium", lat: 33.9535, lng: -118.3392 },
      ],
    },
  ],

  // ─── AT&T Stadium ─────────────────────────────────
  "at-and-t": [
    {
      name: "TRE (Trinity Railway Express)",
      color: "#0077C0",
      stations: [
        { name: "CentrePort/DFW Airport Station", lat: 32.8981, lng: -97.0431 },
        { name: "AT&T Stadium", lat: 32.7473, lng: -97.0945 },
      ],
    },
    {
      name: "TRE",
      color: "#0077C0",
      stations: [
        { name: "Dallas Union Station", lat: 32.7757, lng: -96.8073 },
        { name: "Fort Worth T&P Station", lat: 32.7483, lng: -97.3308 },
        { name: "AT&T Stadium", lat: 32.7473, lng: -97.0945 },
      ],
    },
    {
      name: "DART Rail",
      color: "#0077C0",
      stations: [
        { name: "Dallas Union Station", lat: 32.7757, lng: -96.8073 },
        { name: "AT&T Stadium", lat: 32.7473, lng: -97.0945 },
      ],
    },
    {
      name: "Amtrak",
      color: "#0077C0",
      stations: [
        { name: "Dallas Union Station", lat: 32.7757, lng: -96.8073 },
        { name: "AT&T Stadium", lat: 32.7473, lng: -97.0945 },
      ],
    },
  ],

  // ─── Hard Rock Stadium ─────────────────────────────────
  "hard-rock": [
    {
      name: "Tri-Rail",
      color: "#0077C0",
      stations: [
        { name: "Miami Airport Station", lat: 25.7959, lng: -80.271 },
        { name: "Opa-locka Station", lat: 25.9021, lng: -80.2325 },
        { name: "Hard Rock Stadium", lat: 25.958, lng: -80.2389 },
      ],
    },
    {
      name: "Metrorail (transfer at Tri-Rail)",
      color: "#0077C0",
      stations: [
        { name: "Opa-locka Station", lat: 25.9021, lng: -80.2325 },
        { name: "Hard Rock Stadium", lat: 25.958, lng: -80.2389 },
      ],
    },
    {
      name: "Miami-Dade Bus Routes 95 Express",
      color: "#0077C0",
      stations: [
        { name: "Golden Glades Interchange", lat: 25.9113, lng: -80.2 },
        { name: "Hard Rock Stadium", lat: 25.958, lng: -80.2389 },
      ],
    },
    {
      name: "Metrorail Green/Orange",
      color: "#0077C0",
      stations: [
        { name: "Government Center Station", lat: 25.7743, lng: -80.1937 },
        { name: "Hard Rock Stadium", lat: 25.958, lng: -80.2389 },
      ],
    },
    {
      name: "Metromover",
      color: "#0077C0",
      stations: [
        { name: "Government Center Station", lat: 25.7743, lng: -80.1937 },
        { name: "Hard Rock Stadium", lat: 25.958, lng: -80.2389 },
      ],
    },
    {
      name: "Metrorail Orange Line",
      color: "#0077C0",
      stations: [
        { name: "Miami Airport Station", lat: 25.7959, lng: -80.271 },
        { name: "Hard Rock Stadium", lat: 25.958, lng: -80.2389 },
      ],
    },
  ],

  // ─── NRG Stadium ─────────────────────────────────
  "nrg": [
    {
      name: "Metrorail Red Line",
      color: "#e60f33",
      stations: [
        { name: "Preston", lat: 29.7611, lng: -95.3617 },
        { name: "~wp", lat: 29.7585, lng: -95.3637 },
        { name: "Main Street Square Station SB", lat: 29.7559, lng: -95.3658 },
        { name: "~wp", lat: 29.7235, lng: -95.3901 },
        { name: "~wp", lat: 29.7227, lng: -95.3912 },
        { name: "~wp", lat: 29.7067, lng: -95.403 },
        { name: "~wp", lat: 29.7016, lng: -95.4026 },
        { name: "~wp", lat: 29.6986, lng: -95.4056 },
        { name: "Stadium Park / Astrodome", lat: 29.6859, lng: -95.4034 },
        { name: "NRG Stadium", lat: 29.6847, lng: -95.4107 },
      ],
    },
  ],

  // ─── Mercedes-Benz Stadium ─────────────────────────────────
  "mercedes-benz": [
    {
      name: "MARTA Red/Gold Line",
      color: "#0077C0",
      stations: [
        { name: "Airport Station", lat: 33.6407, lng: -84.4467 },
        { name: "Mercedes-Benz Stadium", lat: 33.7553, lng: -84.4006 },
      ],
    },
  ],

  // ─── Lincoln Financial Field ─────────────────────────────────
  "lincoln-financial": [
    {
      name: "Broad Street Line Local",
      color: "#f26100",
      stations: [
        { name: "City Hall", lat: 39.9525, lng: -75.1641 },
        { name: "~wp", lat: 39.9229, lng: -75.17 },
        { name: "~wp", lat: 39.9229, lng: -75.17 },
        { name: "~wp", lat: 39.9129, lng: -75.1723 },
        { name: "~wp", lat: 39.9129, lng: -75.1723 },
        { name: "NRG", lat: 39.9055, lng: -75.1737 },
        { name: "Lincoln Financial Field", lat: 39.9008, lng: -75.1675 },
      ],
    },
    {
      name: "13th St to Yeadon or Darby TC",
      color: "#5a960a",
      stations: [
        { name: "30th St", lat: 39.9548, lng: -75.1835 },
        { name: "~wp", lat: 39.9538, lng: -75.1751 },
        { name: "~wp", lat: 39.9538, lng: -75.1751 },
        { name: "15th St/City Hall Station", lat: 39.9526, lng: -75.1648 },
        { name: "Lincoln Financial Field", lat: 39.9008, lng: -75.1675 },
      ],
    },
    {
      name: "Lansdale/Doylestown Line",
      color: "#45637a",
      stations: [
        { name: "William H. Gray III 30th Street", lat: 39.9565, lng: -75.1822 },
        { name: "~wp", lat: 39.9563, lng: -75.18 },
        { name: "~wp", lat: 39.9562, lng: -75.1797 },
        { name: "~wp", lat: 39.9557, lng: -75.178 },
        { name: "~wp", lat: 39.9555, lng: -75.1775 },
        { name: "~wp", lat: 39.9554, lng: -75.1768 },
        { name: "Suburban", lat: 39.954, lng: -75.1674 },
        { name: "Lincoln Financial Field", lat: 39.9008, lng: -75.1675 },
      ],
    },
    {
      name: "13th St to 80th St/Eastwick",
      color: "#5a960a",
      stations: [
        { name: "30th St", lat: 39.9548, lng: -75.1835 },
        { name: "~wp", lat: 39.9538, lng: -75.1751 },
        { name: "13th St", lat: 39.9523, lng: -75.1621 },
        { name: "Lincoln Financial Field", lat: 39.9008, lng: -75.1675 },
      ],
    },
    {
      name: "13th St to Darby Transit Center",
      color: "#5a960a",
      stations: [
        { name: "Woodland Av & 60th St", lat: 39.9305, lng: -75.2275 },
        { name: "~wp", lat: 39.9354, lng: -75.2203 },
        { name: "~wp", lat: 39.9391, lng: -75.2151 },
        { name: "~wp", lat: 39.9424, lng: -75.2114 },
        { name: "~wp", lat: 39.9483, lng: -75.2053 },
        { name: "~wp", lat: 39.9499, lng: -75.2017 },
        { name: "~wp", lat: 39.9551, lng: -75.1943 },
        { name: "30th St", lat: 39.9549, lng: -75.1832 },
        { name: "Lincoln Financial Field", lat: 39.9008, lng: -75.1675 },
      ],
    },
  ],

  // ─── Lumen Field ─────────────────────────────────
  "lumen-field": [
    {
      name: "Streetcar: Pioneer Square - Capitol Hill",
      color: "#b50939",
      stations: [
        { name: "5th & Jackson", lat: 47.5992, lng: -122.3268 },
        { name: "Occidental Mall", lat: 47.5992, lng: -122.3334 },
        { name: "Lumen Field", lat: 47.5952, lng: -122.3316 },
      ],
    },
    {
      name: "Link light Rail",
      color: "#28813f",
      stations: [
        { name: "SeaTac/Airport Station", lat: 47.4454, lng: -122.2969 },
        { name: "~wp", lat: 47.4653, lng: -122.2706 },
        { name: "~wp", lat: 47.4664, lng: -122.2691 },
        { name: "Tukwila Int'l Blvd", lat: 47.4639, lng: -122.288 },
        { name: "~wp", lat: 47.4971, lng: -122.2859 },
        { name: "~wp", lat: 47.5095, lng: -122.2784 },
        { name: "~wp", lat: 47.5775, lng: -122.2985 },
        { name: "~wp", lat: 47.5794, lng: -122.3085 },
        { name: "Lumen Field", lat: 47.5952, lng: -122.3316 },
        { name: "International District/Chinatown", lat: 47.5984, lng: -122.3278 },
        { name: "Pioneer Square", lat: 47.6021, lng: -122.3311 },
        { name: "Westlake", lat: 47.6115, lng: -122.3375 },
      ],
    },
    {
      name: "South Bellevue - Redmond Technology",
      color: "#007cad",
      stations: [
        { name: "Westlake", lat: 47.6115, lng: -122.3375 },
        { name: "Pioneer Square", lat: 47.6021, lng: -122.3311 },
        { name: "Lumen Field", lat: 47.5952, lng: -122.3316 },
      ],
    },
  ],

  // ─── Gillette Stadium ─────────────────────────────────
  "gillette": [
    {
      name: "Franklin/Foxboro Line",
      color: "#80276c",
      stations: [
        { name: "South Station", lat: 42.3514, lng: -71.0554 },
        { name: "Boston, Massachusetts", lat: 42.3475, lng: -71.0746 },
        { name: "Ruggles", lat: 42.3364, lng: -71.0896 },
        { name: "~wp", lat: 42.3136, lng: -71.1058 },
        { name: "~wp", lat: 42.2593, lng: -71.1118 },
        { name: "Readville", lat: 42.2378, lng: -71.1343 },
        { name: "~wp", lat: 42.1673, lng: -71.2255 },
        { name: "~wp", lat: 42.1456, lng: -71.2572 },
        { name: "~wp", lat: 42.1264, lng: -71.2627 },
        { name: "~wp", lat: 42.1047, lng: -71.2636 },
        { name: "Foxboro", lat: 42.0951, lng: -71.2615 },
        { name: "Gillette Stadium", lat: 42.0909, lng: -71.2643 },
      ],
    },
    {
      name: "Providence/Stoughton Line",
      color: "#80276c",
      stations: [
        { name: "South Station", lat: 42.3514, lng: -71.0554 },
        { name: "Boston, Massachusetts", lat: 42.3475, lng: -71.0746 },
        { name: "Ruggles", lat: 42.3364, lng: -71.0896 },
        { name: "~wp", lat: 42.3009, lng: -71.1136 },
        { name: "Readville", lat: 42.2389, lng: -71.1334 },
        { name: "~wp", lat: 42.2192, lng: -71.1429 },
        { name: "~wp", lat: 42.134, lng: -71.1761 },
        { name: "Gillette Stadium", lat: 42.0909, lng: -71.2643 },
        { name: "~wp", lat: 41.9054, lng: -71.3132 },
        { name: "~wp", lat: 41.8744, lng: -71.3981 },
        { name: "Providence", lat: 41.8293, lng: -71.4133 },
      ],
    },
    {
      name: "Framingham/Worcester Line",
      color: "#80276c",
      stations: [
        { name: "South Station", lat: 42.3514, lng: -71.0554 },
        { name: "~wp", lat: 42.3472, lng: -71.0573 },
        { name: "~wp", lat: 42.3461, lng: -71.0585 },
        { name: "~wp", lat: 42.3458, lng: -71.0594 },
        { name: "~wp", lat: 42.3463, lng: -71.062 },
        { name: "~wp", lat: 42.3474, lng: -71.0669 },
        { name: "~wp", lat: 42.3477, lng: -71.07 },
        { name: "Boston, Massachusetts", lat: 42.3477, lng: -71.0756 },
        { name: "Gillette Stadium", lat: 42.0909, lng: -71.2643 },
      ],
    },
    {
      name: "Orange Line",
      color: "#ed8b00",
      stations: [
        { name: "Boston, Massachusetts", lat: 42.3473, lng: -71.0757 },
        { name: "~wp", lat: 42.342, lng: -71.0826 },
        { name: "~wp", lat: 42.3316, lng: -71.0952 },
        { name: "~wp", lat: 42.3281, lng: -71.0977 },
        { name: "~wp", lat: 42.3221, lng: -71.1006 },
        { name: "~wp", lat: 42.316, lng: -71.1049 },
        { name: "~wp", lat: 42.3085, lng: -71.1089 },
        { name: "Forest Hills", lat: 42.3007, lng: -71.1142 },
        { name: "Gillette Stadium", lat: 42.0909, lng: -71.2643 },
      ],
    },
  ],

  // ─── BC Place ─────────────────────────────────
  "bc-place": [
    {
      name: "Expo Line",
      color: "#0033a0",
      stations: [
        { name: "~wp", lat: 49.288, lng: -123.1196 },
        { name: "~wp", lat: 49.2877, lng: -123.1163 },
        { name: "~wp", lat: 49.2873, lng: -123.1205 },
        { name: "~wp", lat: 49.2863, lng: -123.1204 },
        { name: "Waterfront", lat: 49.2862, lng: -123.1119 },
        { name: "~wp", lat: 49.2804, lng: -123.1113 },
        { name: "Stadium-Chinatown", lat: 49.2794, lng: -123.1092 },
        { name: "BC Place", lat: 49.2768, lng: -123.1117 },
      ],
    },
    {
      name: "Canada Line",
      color: "#007c9f",
      stations: [
        { name: "YVR–Airport", lat: 49.1943, lng: -123.1786 },
        { name: "~wp", lat: 49.1935, lng: -123.1536 },
        { name: "~wp", lat: 49.1956, lng: -123.1341 },
        { name: "~wp", lat: 49.1969, lng: -123.1232 },
        { name: "~wp", lat: 49.2074, lng: -123.1174 },
        { name: "~wp", lat: 49.2257, lng: -123.1166 },
        { name: "~wp", lat: 49.2455, lng: -123.1155 },
        { name: "Yaletown-Roundhouse Station", lat: 49.2745, lng: -123.122 },
        { name: "BC Place", lat: 49.2768, lng: -123.1117 },
      ],
    },
  ],

  // ─── BMO Field ─────────────────────────────────
  "bmo-field": [
    {
      name: "Lakeshore West Line",
      color: "#98002e",
      stations: [
        { name: "Union Station", lat: 43.6448, lng: -79.3804 },
        { name: "~wp", lat: 43.6442, lng: -79.3825 },
        { name: "~wp", lat: 43.6433, lng: -79.3868 },
        { name: "~wp", lat: 43.6418, lng: -79.3932 },
        { name: "~wp", lat: 43.6406, lng: -79.3986 },
        { name: "~wp", lat: 43.64, lng: -79.4038 },
        { name: "~wp", lat: 43.6387, lng: -79.4089 },
        { name: "Exhibition", lat: 43.6359, lng: -79.4188 },
        { name: "BMO Field", lat: 43.6332, lng: -79.4186 },
      ],
    },
    {
      name: "Harbourfront",
      color: "#ed1c24",
      stations: [
        { name: "~wp", lat: 43.6417, lng: -79.377 },
        { name: "Union", lat: 43.6456, lng: -79.3792 },
        { name: "~wp", lat: 43.6386, lng: -79.3877 },
        { name: "~wp", lat: 43.6358, lng: -79.3981 },
        { name: "~wp", lat: 43.6366, lng: -79.3997 },
        { name: "~wp", lat: 43.6364, lng: -79.4066 },
        { name: "~wp", lat: 43.6373, lng: -79.4132 },
        { name: "Exhibition Loop", lat: 43.6356, lng: -79.4184 },
        { name: "BMO Field", lat: 43.6332, lng: -79.4186 },
      ],
    },
    {
      name: "King",
      color: "#ed1c24",
      stations: [
        { name: "King St West at Bay St West Side", lat: 43.6486, lng: -79.3809 },
        { name: "~wp", lat: 43.6466, lng: -79.39 },
        { name: "~wp", lat: 43.6449, lng: -79.3981 },
        { name: "~wp", lat: 43.6435, lng: -79.405 },
        { name: "~wp", lat: 43.6419, lng: -79.4129 },
        { name: "~wp", lat: 43.6402, lng: -79.4213 },
        { name: "BMO Field", lat: 43.6332, lng: -79.4186 },
        { name: "~wp", lat: 43.639, lng: -79.4274 },
        { name: "Dufferin Gate Loop", lat: 43.6344, lng: -79.4259 },
      ],
    },
    {
      name: "Bathurst",
      color: "#ed1c24",
      stations: [
        { name: "Bathurst Station at Bay 6", lat: 43.6665, lng: -79.4113 },
        { name: "~wp", lat: 43.6616, lng: -79.4099 },
        { name: "~wp", lat: 43.6525, lng: -79.4062 },
        { name: "~wp", lat: 43.6438, lng: -79.4026 },
        { name: "~wp", lat: 43.636, lng: -79.4023 },
        { name: "~wp", lat: 43.6364, lng: -79.4074 },
        { name: "~wp", lat: 43.637, lng: -79.4124 },
        { name: "Exhibition Loop", lat: 43.6362, lng: -79.4156 },
        { name: "BMO Field", lat: 43.6332, lng: -79.4186 },
      ],
    },
    {
      name: "Line 2 Bloor–Danforth",
      color: "#009247",
      stations: [
        { name: "Bathurst", lat: 43.6657, lng: -79.4122 },
        { name: "~wp", lat: 43.6648, lng: -79.4151 },
        { name: "~wp", lat: 43.6648, lng: -79.4151 },
        { name: "~wp", lat: 43.662, lng: -79.4281 },
        { name: "~wp", lat: 43.662, lng: -79.4281 },
        { name: "~wp", lat: 43.6605, lng: -79.4341 },
        { name: "~wp", lat: 43.6605, lng: -79.4341 },
        { name: "Dufferin", lat: 43.6602, lng: -79.4362 },
        { name: "BMO Field", lat: 43.6332, lng: -79.4186 },
      ],
    },
  ],

  // ─── Estadio Azteca ─────────────────────────────────
  "azteca": [
    {
      name: "Tasqueña - Xochimilco",
      color: "#1f5af0",
      stations: [
        { name: "Tasqueña", lat: 19.3438, lng: -99.1395 },
        { name: "~wp", lat: 19.3439, lng: -99.1435 },
        { name: "~wp", lat: 19.3408, lng: -99.1434 },
        { name: "~wp", lat: 19.3324, lng: -99.1408 },
        { name: "~wp", lat: 19.3224, lng: -99.1378 },
        { name: "~wp", lat: 19.3192, lng: -99.1384 },
        { name: "~wp", lat: 19.3085, lng: -99.1421 },
        { name: "Estadio Azteca", lat: 19.3029, lng: -99.1505 },
      ],
    },
    {
      name: "Cuatro Caminos - Tasqueña",
      color: "#0071c1",
      stations: [
        { name: "Zócalo /Tenochtitlan", lat: 19.4325, lng: -99.1323 },
        { name: "~wp", lat: 19.4211, lng: -99.1329 },
        { name: "~wp", lat: 19.4208, lng: -99.133 },
        { name: "~wp", lat: 19.3886, lng: -99.1388 },
        { name: "~wp", lat: 19.386, lng: -99.1392 },
        { name: "Ermita", lat: 19.362, lng: -99.1429 },
        { name: "~wp", lat: 19.3572, lng: -99.1439 },
        { name: "General Anaya", lat: 19.3533, lng: -99.145 },
        { name: "Tasqueña", lat: 19.3437, lng: -99.1396 },
        { name: "Estadio Azteca", lat: 19.3029, lng: -99.1505 },
      ],
    },
  ],

  // ─── Estadio Akron ─────────────────────────────────
  "guadalajara": [
    {
      name: "Linea 2 Juarez-Tetlan",
      color: "#116633",
      stations: [
        { name: "Plaza Universidad", lat: 20.6752, lng: -103.3481 },
        { name: "Juárez", lat: 20.6746, lng: -103.3548 },
        { name: "Estadio Akron", lat: 20.681, lng: -103.4625 },
      ],
    },
  ],

  // ─── Estadio BBVA ─────────────────────────────────
  "monterrey": [
    {
      name: "Línea 1",
      color: "#f2b500",
      stations: [
        { name: "Estación Eloy Cavazos", lat: 25.6797, lng: -100.2641 },
        { name: "~wp", lat: 25.6796, lng: -100.2618 },
        { name: "~wp", lat: 25.6797, lng: -100.2596 },
        { name: "~wp", lat: 25.6798, lng: -100.256 },
        { name: "~wp", lat: 25.6798, lng: -100.2487 },
        { name: "~wp", lat: 25.6798, lng: -100.2481 },
        { name: "Exposición", lat: 25.6795, lng: -100.2455 },
        { name: "Estadio BBVA", lat: 25.6701, lng: -100.2437 },
      ],
    },
  ],

  // ─── Rose Bowl Stadium ─────────────────────────────────
  "rose-bowl": [
    {
      name: "Metro A Line",
      color: "#0072bc",
      stations: [
        { name: "L.A. Union Station", lat: 34.056, lng: -118.2347 },
        { name: "~wp", lat: 34.0698, lng: -118.231 },
        { name: "~wp", lat: 34.0824, lng: -118.2184 },
        { name: "~wp", lat: 34.0987, lng: -118.2059 },
        { name: "~wp", lat: 34.1091, lng: -118.1968 },
        { name: "~wp", lat: 34.1128, lng: -118.1608 },
        { name: "~wp", lat: 34.124, lng: -118.1507 },
        { name: "Memorial Park", lat: 34.148, lng: -118.1477 },
        { name: "Rose Bowl Stadium", lat: 34.1613, lng: -118.1676 },
        { name: "Lake", lat: 34.1518, lng: -118.1316 },
      ],
    },
  ],

  // ─── Levi's Stadium ─────────────────────────────────
  "levis": [
    {
      name: "Capitol Corridor",
      color: "#4573af",
      stations: [
        { name: "Fremont", lat: 37.5591, lng: -122.0074 },
        { name: "~wp", lat: 37.4743, lng: -121.9736 },
        { name: "~wp", lat: 37.4597, lng: -121.9747 },
        { name: "~wp", lat: 37.4405, lng: -121.9762 },
        { name: "Santa Clara, California Great America", lat: 37.4068, lng: -121.967 },
        { name: "Levi's Stadium", lat: 37.4033, lng: -121.9694 },
        { name: "~wp", lat: 37.3856, lng: -121.9527 },
        { name: "~wp", lat: 37.3692, lng: -121.9455 },
        { name: "~wp", lat: 37.3547, lng: -121.939 },
        { name: "Santa Clara, California Transit Center", lat: 37.3532, lng: -121.9364 },
        { name: "San Jose Diridon", lat: 37.3299, lng: -121.9024 },
      ],
    },
    {
      name: "Altamont Commuter Express",
      color: "#740a6d",
      stations: [
        { name: "San Jose Diridon", lat: 37.3307, lng: -121.9024 },
        { name: "~wp", lat: 37.3345, lng: -121.9046 },
        { name: "~wp", lat: 37.3415, lng: -121.9131 },
        { name: "~wp", lat: 37.3517, lng: -121.9331 },
        { name: "Santa Clara, California Transit Center", lat: 37.3535, lng: -121.9363 },
        { name: "~wp", lat: 37.3558, lng: -121.9413 },
        { name: "~wp", lat: 37.3751, lng: -121.9462 },
        { name: "~wp", lat: 37.4019, lng: -121.9636 },
        { name: "Levi's Stadium", lat: 37.4033, lng: -121.9694 },
        { name: "Santa Clara, California Great America", lat: 37.4068, lng: -121.9671 },
      ],
    },
    {
      name: "Berryessa/North San Jose to Richmond",
      color: "#f29130",
      stations: [
        { name: "Union City", lat: 37.5903, lng: -122.0166 },
        { name: "~wp", lat: 37.5801, lng: -122.0033 },
        { name: "~wp", lat: 37.5697, lng: -121.9898 },
        { name: "Fremont", lat: 37.5575, lng: -121.9766 },
        { name: "~wp", lat: 37.5532, lng: -121.9629 },
        { name: "~wp", lat: 37.5475, lng: -121.9569 },
        { name: "~wp", lat: 37.5443, lng: -121.9556 },
        { name: "~wp", lat: 37.539, lng: -121.9543 },
        { name: "Levi's Stadium", lat: 37.4033, lng: -121.9694 },
        { name: "Milpitas", lat: 37.4098, lng: -121.8908 },
      ],
    },
    {
      name: "Local Weekday",
      color: "#a7a8a8",
      stations: [
        { name: "Palo Alto", lat: 37.4434, lng: -122.1647 },
        { name: "~wp", lat: 37.427, lng: -122.1383 },
        { name: "~wp", lat: 37.3917, lng: -122.0691 },
        { name: "~wp", lat: 37.3874, lng: -122.0574 },
        { name: "~wp", lat: 37.3705, lng: -121.9875 },
        { name: "~wp", lat: 37.3705, lng: -121.9781 },
        { name: "Levi's Stadium", lat: 37.4033, lng: -121.9694 },
        { name: "Santa Clara, California Transit Center", lat: 37.3532, lng: -121.9361 },
        { name: "~wp", lat: 37.3334, lng: -121.9036 },
        { name: "San Jose Diridon", lat: 37.3292, lng: -121.903 },
      ],
    },
    {
      name: "Berryessa/North San Jose to Daly City",
      color: "#339933",
      stations: [
        { name: "Fremont", lat: 37.5575, lng: -121.9766 },
        { name: "~wp", lat: 37.5541, lng: -121.9653 },
        { name: "~wp", lat: 37.5516, lng: -121.9609 },
        { name: "~wp", lat: 37.5451, lng: -121.9558 },
        { name: "~wp", lat: 37.5306, lng: -121.9536 },
        { name: "~wp", lat: 37.5047, lng: -121.9407 },
        { name: "~wp", lat: 37.4934, lng: -121.9349 },
        { name: "Milpitas", lat: 37.4098, lng: -121.8908 },
        { name: "Levi's Stadium", lat: 37.4033, lng: -121.9694 },
      ],
    },
  ],

};
